spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: sdllove1314

  thymeleaf:
    #是否缓存
    cache: false
    # 在构建URL时预先查看名称的前缀
    prefix: classpath:/templates/
    # 构建URL时附加查看名称的后缀
    suffix: .html
  #mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
